### ISSUE TITLE
Doesn't render on IOS

### ISSUE THREAD

**Issue by OmarHassan25** [DelcoigneYves/Xam.Plugin.ImageButton#1]
The lib doesn't render on ios, I am not using full linking, any help?

**Comment by DelcoigneYves** [comment]
Hey, thanks for using my library!

Have you tried reproducing your issue with the sample project included in the source code?

**Comment by OmarHassan25** [comment]
The sample does not build for me, all I did is creating a new forms app and adding the lib using NuGet. 
It is working well on Andfori but no render on ios. Could you please provide a working sample using NuGet?

**Comment by OmarHassan25** [comment]
I am sorry, i missed this line 			ImageButtonRenderer.Init();
